/**
 * The rule registry. Every check — conformance and safety — is registered here,
 * and RULES.md is generated by walking it, so the documentation cannot drift
 * from what actually runs.
 */
import type { Rule } from "./rules/types.js";
import type { RuleMeta } from "./schema/finding.js";

import { rule as c0 } from "./probe/c0-protocol-era.js";

/** Lane A — conformance. */
export const CONFORMANCE_RULES: readonly Rule[] = [c0];

/** Lane B — safety. */
export const SAFETY_RULES: readonly Rule[] = [];

export const ALL_RULES: readonly Rule[] = [...CONFORMANCE_RULES, ...SAFETY_RULES];

export const ALL_RULE_META: readonly RuleMeta[] = ALL_RULES.map((r) => r.meta);

export function ruleById(id: string): Rule | undefined {
  return ALL_RULES.find((r) => r.meta.id === id);
}
