/**
 * The rule registry. Every check — conformance and safety — is registered here,
 * and RULES.md is generated by walking it, so the documentation cannot drift
 * from what actually runs.
 */
import type { Rule } from "./rules/types.js";
import type { RuleMeta } from "./schema/finding.js";

import { rule as c0 } from "./probe/c0-protocol-era.js";
import { rule as c1 } from "./probe/c1-discover.js";
import { rule as c2 } from "./probe/c2-tools-hygiene.js";
import { rule as c3 } from "./probe/c3-meta-validation.js";
import { c4, c5, c6 } from "./probe/c4-c5-c6.js";
import { c7, c8 } from "./probe/c7-c8.js";

import { rule as s1 } from "./rules/s1-tool-poisoning.js";
import { rule as s2 } from "./rules/s2-destructive.js";
import { rule as s3 } from "./rules/s3-credentials.js";
import { rule as s4 } from "./rules/s4-schema-egress.js";
import { s5, s6, s7 } from "./rules/s5-s6-s7.js";

/** Lane A — conformance. */
export const CONFORMANCE_RULES: readonly Rule[] = [c0, c1, c2, c3, c4, c5, c6, c7, c8];

/** Lane B — safety. */
export const SAFETY_RULES: readonly Rule[] = [s1, s2, s3, s4, s5, s6, s7];

export const ALL_RULES: readonly Rule[] = [...CONFORMANCE_RULES, ...SAFETY_RULES];

export const ALL_RULE_META: readonly RuleMeta[] = ALL_RULES.map((r) => r.meta);

export function ruleById(id: string): Rule | undefined {
  return ALL_RULES.find((r) => r.meta.id === id);
}
